### ISSUE TITLE
theme.css link returns 404

### ISSUE THREAD

**Issue by graves501** [dracula/nextcloud#2]
At https://draculatheme.com/nextcloud the `theme.css` link in the install instructions points to https://draculatheme.com/theme.css which returns a `404` response.

The correct link should point to https://raw.githubusercontent.com/dracula/nextcloud/main/theme.css !

**Comment by SIMULATAN** [comment]
Thanks a lot for reporting this!
I honestly don't know when it'll update on the website, but I believe the next rebuild should do that.
